// Math.random() uses a seeded PRNG — predictable if seed or any output is known
// We simulate a Linear Congruential Generator (LCG) to demonstrate predictability
// LCG: X(n+1) = (a * X(n) + c) mod m
const LCG_A = 1664525;
const LCG_C = 1013904223;
const LCG_M = 2 ** 32;

let lcgState = null;   // seed
let lastToken = null;
let tokenTimestamp = null;

const requestForm    = document.getElementById('requestForm');
const predictBtn     = document.getElementById('predictBtn');
const tokenSection   = document.getElementById('tokenSection');
const tokenDisplay   = document.getElementById('tokenDisplay');
const predictResult  = document.getElementById('predictResult');
const predictedToken = document.getElementById('predictedToken');
const verifyResult   = document.getElementById('verifyResult');
const explanationBox = document.getElementById('explanationBox');

function lcgNext(state) {
  return ((LCG_A * state + LCG_C) >>> 0); // unsigned 32-bit
}

function mathRandomLike(state) {
  return (state >>> 0) / LCG_M;
}

function generateToken(rngOutput) {
  // Simulated: token = hex of floor(rng * 0xFFFFFFFF).toString(16)
  const raw = Math.floor(rngOutput * 0xFFFFFFFF);
  return raw.toString(16).padStart(8, '0');
}

requestForm.addEventListener('submit', (e) => {
  e.preventDefault();
  // Seed from timestamp (common insecure pattern)
  tokenTimestamp = Date.now();
  lcgState = tokenTimestamp & 0xFFFFFFFF; // low 32 bits of timestamp as seed

  const rng = mathRandomLike(lcgNext(lcgState));
  lastToken = generateToken(rng);

  tokenDisplay.textContent = lastToken;
  tokenSection.classList.remove('hidden');
  predictResult.classList.add('hidden');
  explanationBox.classList.add('hidden');
});

predictBtn.addEventListener('click', async () => {
  if (!lastToken || !tokenTimestamp) {
    predictedToken.textContent = 'Generate a token first.';
    predictResult.classList.remove('hidden');
    return;
  }

  predictedToken.textContent = 'Predicting...';
  predictResult.classList.remove('hidden');

  // Simulate attack: try timestamps near observed generation time (±5 seconds)
  const window = 5000;
  const start  = tokenTimestamp - window;
  const end    = tokenTimestamp + window;

  await sleep(400); // simulate work

  for (let ts = start; ts <= end; ts += 1) {
    const seed = ts & 0xFFFFFFFF;
    const rng  = mathRandomLike(lcgNext(seed));
    const tok  = generateToken(rng);
    if (tok === lastToken) {
      predictedToken.textContent = tok;
      verifyResult.textContent = `SUCCESS: Token matched seed ${ts} (offset: ${ts - tokenTimestamp}ms from observed timestamp).`;
      verifyResult.className = 'msg success';
      showExplanation(ts);
      return;
    }
  }
  predictedToken.textContent = 'Not found in ±5s window.';
  verifyResult.textContent = 'Try again with a freshly generated token.';
  verifyResult.className = 'msg';
});

function showExplanation(seed) {
  explanationBox.classList.remove('hidden');
  explanationBox.innerHTML = `
    <h3>Insecure Randomness — Predictable Token Generation</h3>
    <p>The token was regenerated by brute-forcing timestamps near the observed generation time. <code>Math.random()</code> and timestamp-seeded PRNGs are not cryptographically secure.</p>
    <ul>
      <li><strong>Root cause:</strong> Using <code>Math.random()</code>, <code>Date.now()</code>, or predictable seeds for security tokens (session IDs, password reset links, CSRF tokens).</li>
      <li><strong>Attack:</strong> If an attacker can observe one token (or guess the seed range), they can predict past and future tokens — allowing account takeover via forged reset links.</li>
      <li><strong>Fix:</strong> Use <code>crypto.getRandomValues()</code> (browser) or <code>crypto.randomBytes()</code> (Node.js) — cryptographically secure random sources that cannot be predicted even with knowledge of previous outputs.</li>
      <li><strong>Minimum entropy:</strong> Password reset tokens should be at least 128 bits (16 bytes) from a CSPRNG.</li>
    </ul>`;
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }
